export const appConfig = {
  REDIS_CLUSTER_URL: process.env.REDIS_CLUSTER_URL,
  BUREAU_USER_INFO_URL: process.env.BUREAU_USER_INFO_URL,
  BUREAU_CLIENT_ID: process.env.BUREAU_CLIENT_ID,
  BUREAU_CLIENT_SECRET: process.env.BUREAU_CLIENT_SECRET,
};
