//loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const DISCOVER_REQUEST = 'DISCOVER_REQUEST';
export const DISCOVER_SUCCESS = 'DISCOVER_SUCCESS';
export const DISCOVER_FAILURE = 'DISCOVER_FAILURE';

export const INITIATE_REQUEST = 'INITIATE_REQUEST';
export const INITIATE_SUCCESS = 'INITIATE_SUCCESS';
export const INITIATE_FAILURE = 'INITIATE_FAILURE';

export const FINALIZE_REQUEST = 'FINALIZE_REQUEST';
export const FINALIZE_SUCCESS = 'FINALIZE_SUCCESS';
export const FINALIZE_FAILURE = 'FINALIZE_FAILURE';

export const OTP_GENERATE_REQUEST = 'OTP_GENERATE_REQUEST';
export const OTP_GENERATE_SUCCESS = 'OTP_GENERATE_SUCCESS';
export const OTP_GENERATE_FAILURE = 'OTP_GENERATE_FAILURE';

export const OTP_VERIFY_REQUEST = 'OTP_VERIFY_REQUEST';
export const OTP_VERIFY_SUCCESS = 'OTP_VERIFY_SUCCESS';
export const OTP_VERIFY_FAILURE = 'OTP_VERIFY_FAILURE';

export const USERINFO_REQUEST = 'USERINFO_REQUEST';
export const USERINFO_SUCCESS = 'USERINFO_SUCCESS';
export const USERINFO_FAILURE = 'USERINFO_FAILURE';